### ISSUE TITLE
Instructions on how to build/install for Python 3

### ISSUE THREAD

**Issue by mpetitjean** [OnionIoT/i2c-exp-driver#26]
Hello, 

I seem to be unable to find any instructions to build the driver for use with python3. Is there any available out there, or should it be created ?

**Comment by alec-WaterIQTech** [comment]
@mpetitjean Did you ever figure out a way to get it working for py3?

**Comment by greenbreakfast** [comment]
@alec-WaterIQTech Python3 versions of these modules are available. See https://onion.io/2bt-python3-modules/

See the package makefile for info on how to build for python3: https://github.com/OnionIoT/OpenWRT-Packages/blob/openwrt-18.06/i2c-exp-driver/Makefile
